SuperStore/Controllers/CartController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SuperStore.Data.Models;
using SuperStore.Services.Services;
using SuperStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperStore.Web.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ShoppingCartService _shoppingCartService;
        private readonly IMapper _mapper;

        public CartController(ShoppingCartService shoppingCartService, IMapper mapper)
        {
            _shoppingCartService = shoppingCartService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var userCart = await _shoppingCartService.GetUserShoppingCartAsync(this.User);
            var cartViewModel = _mapper.Map<ShoppingCart, ShoppingCartViewModel>(userCart, opt => opt.Items["cart"] = userCart);


            return View(cartViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int productId, int amount)
        {
            if (await _shoppingCartService.AddProductAsync(productId, amount, this.User) == null)
                return BadRequest();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int productId)
        {
            await _shoppingCartService.RemoveProductAsync(productId, this.User);

            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAmount(int shoppingCartItemId, int newAmount)
        {
            if (await _shoppingCartService.ModifyShoppingCartItemAmountAsync(shoppingCartItemId, newAmount, User) == null)
                return BadRequest();

            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ClearNotifications()
        {
            await _shoppingCartService.ClearNotificationsAsync(User);


            return RedirectToAction("Index");
        }
    }


    
}

SuperStore/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SuperStore.Data.Models;
using SuperStore.Services.Services;
using SuperStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperStore.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly IMapper _mapper;

        public CategoryController(CategoryService categoryService, ProductService productService
            , ShoppingCartService shoppingCartService, IMapper mapper)
        {
            _categoryService = categoryService;
            _productService = productService;
            _shoppingCartService = shoppingCartService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.GetAllCategoriesAsync());
        }

        public async Task<IActionResult> Products(int categoryId)
        {
            ViewBag.CategoryName = (await _categoryService.GetCategoryByIdAsync(categoryId)).CategoryName;
            var products = await _productService.GetProductsByCategoryAsync(categoryId);
            var userCart = await _shoppingCartService.GetUserShoppingCartAsync(this.User);
            var productViewModels = _mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products, opt => opt.Items["cart"] = userCart);
            return View(productViewModels);
        }
    }
}

SuperStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SuperStore.Services.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperStore.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderService _orderService;

        public OrderController(OrderService orderService)
        {
            _orderService = orderService;
        }
        public async Task<IActionResult> Index()
        {
            var orders = await _orderService.GetUserOrderHistoryAsync(this.User);
            return View(orders);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakeOrder()
        {
            await _orderService.MakeAnOrderAsync(this.User);
            return RedirectToAction("Index");
        }
    }
}

SuperStore/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SuperStore.Data.Models;
using SuperStore.Services.Services;
using SuperStore.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperStore.Web.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly IMapper _mapper;

        public ProductController(CategoryService categoryService, ProductService productService, ShoppingCartService shoppingCartService,
            IMapper mapper)
        {
            _categoryService = categoryService;
            _productService = productService;
            _shoppingCartService = shoppingCartService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetProductsAsync();
            var userCart = await _shoppingCartService.GetUserShoppingCartAsync(this.User);
            var productViewModels = _mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products, opt => opt.Items["cart"] = userCart);

            return View(productViewModels);
        }


        [HttpGet]
        public async Task<IActionResult> Create(ProductViewModel receivedProduct)
        {
            if (!string.IsNullOrEmpty(receivedProduct.Title))
            {
                return View(receivedProduct);
            }

            ModelState.Clear();
            var productViewModel = new ProductViewModel
            {
                CategorySelectList =
                new SelectList(await _categoryService.GetAllCategoriesAsync(), "CategoryId", "CategoryName")
            };
            return View(productViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Create")]
        public async Task<IActionResult> Create_Post(ProductViewModel productViewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create", productViewModel);
            }

            bool validCategory = (await _categoryService.GetAllCategoriesAsync())
                .Any(c => c.CategoryId == productViewModel.CategoryId);

            if (!validCategory)
            {
                ModelState.AddModelError("CategoryId", "Pleas Enter a valid Category");
                return RedirectToAction("Create", productViewModel);
            }
            
            productViewModel.ImageFormFile = Request.Form.Files["ImageFile"];
            

            var productModel = _mapper.Map<Product>(productViewModel);

            if (await _productService.CreateProductAsync(productModel, User) == null)
            {
                return BadRequest();
            }

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Product product = await _productService.GetProductByIdAsync((int) id);

            if (product == null)
            {
                return NotFound();
            }    

            var userCart = await _shoppingCartService.GetUserShoppingCartAsync(this.User);

            var productViewModel = _mapper.Map<ProductViewModel>(product, opt => opt.Items["cart"] = userCart);
            var viewModel = new ProductDetailsViewModel { Product = productViewModel };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddReview(Review review)
        {

            if (await _productService.AddReviewAsync(review, User) == null)
            {
                return BadRequest();
            }
            return RedirectToAction("Details", new { id = review.ProductId });
        }

    }
}

SuperStore/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/17c1561542.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">SuperStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between align-items-center">
                    <div class="justify-content-between">
                        @if (SignInManager.IsSignedIn(User)) { 

                            <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Cart" asp-action="Index">
                                    Cart <i class="fas fa-shopping-cart fa-lg"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Order" asp-action="Index">
                                    Order History
                                </a>
                            </li>
                        </ul>
                        }
                        
                    </div>
                    <div class="justify-content-end">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SuperStore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>